---
- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Set variable avi_credentials
      set_fact:
        avi_credentials: >
          {'api_version': "{{ avi_version }}",
           'controller': "{{ avi_controller }}",
           'password': "{{ avi_password }}",
           'username': "admin"}
      when:
        - avi_version is defined
        - avi_controller is defined
        - avi_password is defined

    - name: Configure Avi Cloud without IPAM - no_access_vcenter
      avi_cloud:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ avi.cloud.name }}"
        vtype: "{{ avi.cloud.type }}"
      register: output_cloud_no_access_vcenter
      when:
        - avi.cloud.name is defined
        - avi.cloud.type is defined

    - set_fact:
        cloud_no_access_vcenter_uuid: "{{ output_cloud_no_access_vcenter.obj.uuid }}"
      when:
        - output_cloud_no_access_vcenter is defined