---
- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Print Avi version
      debug:
        msg: "{{ avi_version.value }}"

    - name: Print Avi controller IP
      debug:
        msg: "{{ controllers_ip.value.0 }}"

    - name: Set variable avi_credentials
      set_fact:
        avi_credentials: >
          {'api_version': "{{ avi_version.value }}",
           'controller': "{{ controllers_ip.value.0 }}",
           'password': "{{ avi_password }}",
           'username': "admin"}
      when:
        - avi_version.value is defined
        - controllers_ip.value.0 is defined
        - avi_password is defined

    - name: Defining variable vcenter_configuration
      set_fact:
        vcenter_configuration:
          username: "{{ avi.cloud.vcenter.username }}"
          password: "{{ vsphere_password }}"
          vcenter_url: "{{ avi.cloud.vcenter.server }}"
          privilege: WRITE_ACCESS
          datacenter: "{{ avi.cloud.vcenter.dc }}"
      when:
        - avi.cloud.vcenter.username is defined
        - vsphere_password is defined
        - avi.cloud.vcenter.server is defined
        - avi.cloud.vcenter.dc is defined

    - name: Configure Avi Cloud
      avi_cloud:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        avi_api_update_method: patch
        avi_api_patch_op: add
        name:  "{{ avi.cloud.name }}"
        vtype: "{{ avi.cloud.type }}"
        vcenter_configuration: "{{ vcenter_configuration }}"
        dhcp_enabled: "{{ avi.cloud.vcenter.management_network.dhcp_enabled }}"
        ipam_provider_ref: "/api/ipamdnsproviderprofile/?name={{ avi.cloud.ipam_provider_ref }}"
        dns_provider_ref: "/api/ipamdnsproviderprofile/?name={{ avi.cloud.dns_provider_ref }}"
      register: output_cloud_vmw
      when:
        - avi.cloud.name is defined
        - avi.cloud.type is defined
        - vcenter_configuration is defined
        - avi.cloud.vcenter.management_network.dhcp_enabled is defined
        - avi.cloud.ipam_provider_ref is defined
        - avi.cloud.dns_provider_ref is defined